# Fashion-MNIST preparation (convertion to binary classification)

In [8]:
import pandas as pd
pd.options.mode.chained_assignment = None

In [9]:
data = pd.read_csv('https://www.openml.org/data/get_csv/18238735/phpnBqZGZ')

In [10]:
data

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,class
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
1,0,0,0,0,0,1,0,0,0,0,...,114,130,76,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,22,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,33,96,...,0,0,0,0,0,0,0,0,0,3
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
69996,0,0,0,0,0,0,0,0,0,31,...,0,0,0,0,0,0,0,0,0,1
69997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
69998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
69999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5

In [12]:
c=6
class_ = data[data['class']==c]
class_['class'] = 1
other = data[data['class']!=c]

In [13]:
class_

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,class
18,0,0,0,2,0,2,0,0,6,36,...,0,0,0,15,160,100,0,0,0,1
32,0,0,0,0,0,1,2,0,0,0,...,0,0,0,0,0,0,0,0,0,1
33,0,0,0,0,0,0,0,0,0,1,...,0,0,17,1,0,0,0,0,0,1
39,0,0,0,0,0,0,0,2,3,0,...,0,0,67,109,21,0,0,0,0,1
40,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69962,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
69971,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,1
69977,0,0,0,1,1,0,0,32,54,127,...,27,28,56,57,0,0,0,0,0,1
69979,0,0,0,0,0,0,0,8,50,64,...,47,111,12,0,1,0,0,0,0,1
69991,0,0,0,0,0,0,0,0,29,59,...,0,0,0,0,0,0,0,0,0,1

In [14]:
cat = 0

for i in range(10):
    if(cat!=c and cat<10):
        index = other[other['class'] == cat].index[:6222]
        other.drop(index, inplace = True)    
    cat+=1

other['class'] = 0

other.drop(other.index[:2], inplace = True)

In [15]:
other

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,class
62067,0,0,0,0,0,0,0,0,0,2,...,0,0,153,204,188,47,0,0,0,0
62073,0,0,0,0,15,15,15,11,18,7,...,0,10,15,15,15,0,0,0,0,0
62079,0,0,0,0,0,0,0,0,2,0,...,0,0,96,94,112,16,0,0,0,0
62081,0,0,0,0,0,0,0,0,3,1,...,2,0,0,131,49,0,0,0,0,0
62082,0,0,0,0,0,1,3,0,0,0,...,0,0,0,0,30,112,118,16,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69996,0,0,0,0,0,0,0,0,0,31,...,0,0,0,0,0,0,0,0,0,0
69997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
new = pd.concat([class_, other], ignore_index=True)
new = new.sample(frac=1).reset_index(drop=True)
new

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,class
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,126,118,31,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,0,58,14,12,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,107,76,111,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,39,72,...,170,170,92,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13995,0,0,0,0,0,0,0,128,157,180,...,191,126,0,0,0,0,0,0,0,0
13996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13997,0,0,0,0,0,0,0,0,0,0,...,0,0,40,77,48,2,0,0,0,0
13998,0,0,0,0,0,0,0,0,0,0,...,0,40,141,151,94,35,0,0,0,1
13999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
new.to_csv('Fashion-MNIST-binary.csv', index=False)